objects = alu.v aludec.v controller.v datapath.v flopenr.v flopr.v maindec.v mem.v mips.v mux2.v mux3.v mux4.v regfile.v signext.v sl2.v top.v tb.v
build:
	iverilog -o output -g 2012 $(objects)
clean:
	rm out