objects = alu.v aludecoder.v controlunit.v datapath.v ffenabled.v ff.v maindecoder.v memory.v multicycle.v mux2.v mux3.v mux4.v register.v signext.v sl.v topmodule.v testbench.v
build:
	iverilog -o output -g 2012 $(objects)
clean:
	rm out